<?php

namespace Zoop\Utils;

class Currency
{
    private static $currencies = [
        'USD' => ['$', 'US dollar'],
        'EUR' => ['€', 'Euro'],
        'JPY' => ['¥', 'Japanese yen'],
        'GBP' => ['£', 'British pound'],
        'CHF' => ['Fr', 'Swiss franc'],
        'AFN' => ['؋', 'Afghan afghani'],
        'ALL' => ['L', 'Albanian lek'],
        'DZD' => ['د.ج', 'Algerian dinar'],
        'AOA' => ['Kz', 'Angolan kwanza'],
        'ARS' => ['$', 'Argentine peso'],
        'AMD' => ['դր.', 'Armenian dram'],
        'AWG' => ['ƒ', 'Aruban florin'],
        'AUD' => ['$', 'Australian dollar'],
        'AZN' => ['m', 'Azerbaijani manat'],
        'BSD' => ['$', 'Bahamian dollar'],
        'BHD' => ['.د.ب', 'Bahraini dinar'],
        'BDT' => ['৳', 'Bangladeshi taka'],
        'BBD' => ['$', 'Barbadian dollar'],
        'BYR' => ['Br', 'Belarusian ruble'],
        'BZD' => ['$', 'Belize dollar'],
        'BMD' => ['$', 'Bermudian dollar'],
        'BTN' => ['Nu.', 'Bhutanese ngultrum'],
        'BOB' => ['Bs.', 'Bolivian boliviano'],
        'BAM' => ['KM', 'Bosnia Herzegovina mark'],
        'BWP' => ['P', 'Botswana pula'],
        'BRL' => ['R$', 'Brazilian real'],
        'BND' => ['$', 'Brunei dollar'],
        'BGN' => ['лв', 'Bulgarian lev'],
        'BIF' => ['Fr', 'Burundian franc'],
        'KHR' => ['៛', 'Cambodian riel'],
        'CAD' => ['$', 'Canadian dollar'],
        'CVE' => ['$', 'Cape Verdean escudo'],
        'KYD' => ['$', 'Cayman Islands dollar'],
        'XAF' => ['Fr', 'Central African CFA franc'],
        'CLP' => ['$', 'Chilean peso'],
        'CNY' => ['元', 'Chinese yuan'],
        'COP' => ['$', 'Colombian peso'],
        'KMF' => ['Fr', 'Comorian franc'],
        'CDF' => ['Fr', 'Congolese franc'],
        'CRC' => ['₡', 'Costa Rican colón'],
        'HRK' => ['kn', 'Croatian kuna'],
        'XPF' => ['F', 'CFP franc'],
        'CUC' => ['$', 'Cuban convertible peso'],
        'CUP' => ['$', 'Cuban peso'],
        'CMG' => ['ƒ', 'Curaçao and Sint Maarten guilder'],
        'CZK' => ['Kč', 'Czech koruna'],
        'DKK' => ['kr', 'Danish krone'],
        'DJF' => ['Fr', 'Djiboutian franc'],
        'DOP' => ['$', 'Dominican peso'],
        'XCD' => ['$', 'East Caribbean dollar'],
        'EGP' => ['ج.م', 'Egyptian pound'],
        'ERN' => ['Nfk', 'Eritrean nakfa'],
        'EEK' => ['kr', 'Estonian kroon'],
        'ETB' => ['Br', 'Ethiopian birr'],
        'FKP' => ['£', 'Falkland Islands pound'],
        'FJD' => ['$', 'Fijian dollar'],
        'GMD' => ['D', 'Gambian dalasi'],
        'GEL' => ['ლ', 'Georgian lari'],
        'GHS' => ['₵', 'Ghanaian cedi'],
        'GIP' => ['£', 'Gibraltar pound'],
        'GTQ' => ['Q', 'Guatemalan quetzal'],
        'GNF' => ['Fr', 'Guinean franc'],
        'GYD' => ['$', 'Guyanese dollar'],
        'HTG' => ['G', 'Haitian gourde'],
        'HNL' => ['L', 'Honduran lempira'],
        'HKD' => ['$', 'Hong Kong dollar'],
        'HUF' => ['Ft', 'Hungarian forint'],
        'ISK' => ['kr', 'Icelandic króna'],
        'INR' => ['‎₹', 'Indian rupee'],
        'IDR' => ['Rp', 'Indonesian rupiah'],
        'IRR' => ['﷼', 'Iranian rial'],
        'IQD' => ['ع.د', 'Iraqi dinar'],
        'ILS' => ['₪', 'Israeli new shekel'],
        'JMD' => ['$', 'Jamaican dollar'],
        'JOD' => ['د.ا', 'Jordanian dinar'],
        'KZT' => ['₸', 'Kazakhstani tenge'],
        'KES' => ['Sh', 'Kenyan shilling'],
        'KWD' => ['د.ك', 'Kuwaiti dinar'],
        'KGS' => ['лв', 'Kyrgyzstani som'],
        'LAK' => ['₭', 'Lao kip'],
        'LVL' => ['Ls', 'Latvian lats'],
        'LBP' => ['ل.ل', 'Lebanese pound'],
        'LSL' => ['L', 'Lesotho loti'],
        'LRD' => ['$', 'Liberian dollar'],
        'LYD' => ['ل.د', 'Libyan dinar'],
        'LTL' => ['Lt', 'Lithuanian litas'],
        'MOP' => ['P', 'Macanese pataca'],
        'MKD' => ['ден', 'Macedonian denar'],
        'MGA' => ['Ar', 'Malagasy ariary'],
        'MWK' => ['MK', 'Malawian kwacha'],
        'MYR' => ['RM', 'Malaysian ringgit'],
        'MVR' => ['ރ.', 'Maldivian rufiyaa'],
        'MRO' => ['UM', 'Mauritanian ouguiya'],
        'MUR' => ['₨', 'Mauritian rupee'],
        'MXN' => ['$', 'Mexican peso'],
        'MDL' => ['L', 'Moldovan leu'],
        'MNT' => ['₮', 'Mongolian tögrög'],
        'MAD' => ['د.م.', 'Moroccan dirham'],
        'MZN' => ['MTn', 'Mozambican metical'],
        'MMK' => ['K', 'Myanma kyat'],
        'NAD' => ['$', 'Namibian dollar'],
        'NPR' => ['₨', 'Nepalese rupee'],
        'ANG' => ['ƒ', 'Netherlands Antillean guilder'],
        'TWD' => ['$', 'New Taiwan dollar'],
        'NZD' => ['$', 'New Zealand dollar'],
        'NIO' => ['C$', 'Nicaraguan córdoba'],
        'NGN' => ['₦', 'Nigerian naira'],
        'KPW' => ['₩', 'North Korean won'],
        'NOK' => ['kr', 'Norwegian krone'],
        'OMR' => ['ر.ع.', 'Omani rial'],
        'PKR' => ['₨', 'Pakistani rupee'],
        'PAB' => ['B/.', 'Panamanian balboa'],
        'PGK' => ['K', 'Papua New Guinean kina'],
        'PYG' => ['₲', 'Paraguayan guaraní'],
        'PEN' => ['S/.', 'Peruvian nuevo sol'],
        'PHP' => ['₱', 'Philippine peso'],
        'PLN' => ['zł', 'Polish złoty'],
        'QAR' => ['ر.ق', 'Qatari riyal'],
        'RON' => ['L', 'Romanian leu'],
        'RUB' => ['руб.', 'Russian ruble'],
        'RWF' => ['Fr', 'Rwandan franc'],
        'SHP' => ['£', 'Saint Helena pound'],
        'SVC' => ['₡', 'Salvadoran colón'],
        'WST' => ['T', 'Samoan tala'],
        'STD' => ['Db', 'São Tomé and Príncipe dobra'],
        'SAR' => ['ر.س', 'Saudi riyal'],
        'RSD' => ['дин. or din.', 'Serbian dinar'],
        'SCR' => ['₨', 'Seychellois rupee'],
        'SLL' => ['Le', 'Sierra Leonean leone'],
        'SGD' => ['$', 'Singapore dollar'],
        'SBD' => ['$', 'Solomon Islands dollar'],
        'SOS' => ['Sh', 'Somali shilling'],
        'ZAR' => ['R', 'South African rand'],
        'KRW' => ['₩', 'South Korean won'],
        'LKR' => ['Rs', 'Sri Lankan rupee'],
        'SDG' => ['جنيه سوداني', 'Sudanese pound'],
        'SRD' => ['$', 'Surinamese dollar'],
        'SZL' => ['L', 'Swazi lilangeni'],
        'SEK' => ['kr', 'Swedish krona'],
        'SYP' => ['ل.س', 'Syrian pound'],
        'TJS' => ['ЅМ', 'Tajikistani somoni'],
        'TZS' => ['Sh', 'Tanzanian shilling'],
        'THB' => ['฿', 'Thai baht'],
        'TOP' => ['T$', 'Tongan paʻanga'],
        'TTD' => ['$', 'Trinidad and Tobago dollar'],
        'TND' => ['د.ت', 'Tunisian dinar'],
        'TRY' => ['TL', 'Turkish lira'],
        'TMM' => ['m', 'Turkmenistani manat'],
        'UGX' => ['Sh', 'Ugandan shilling'],
        'UAH' => ['₴', 'Ukrainian hryvnia'],
        'AED' => ['د.إ', 'United Arab Emirates dirham'],
        'UYU' => ['$', 'Uruguayan peso'],
        'UZS' => ['лв', 'Uzbekistani som'],
        'VUV' => ['Vt', 'Vanuatu vatu'],
        'VEF' => ['Bs F', 'Venezuelan bolívar'],
        'VND' => ['₫', 'Vietnamese đồng'],
        'XOF' => ['Fr', 'West African CFA franc'],
        'YER' => ['﷼', 'Yemeni rial'],
        'ZMK' => ['ZK', 'Zambian kwacha'],
        'ZWL' => ['$', 'Zimbabwean dollar'],
    ];

    /**
     * @param string $currencyCode
     * @return string
     */
    public static function getCurrencySymbol($currencyCode)
    {
        if (isset(self::$currencies[$currencyCode])) {
            return self::$currencies[$currencyCode][0];
        }
        return '';
    }

    /**
     * @param string $currencyCode
     * @return string
     */
    public static function getCurrencyName($currencyCode)
    {
        if (isset(self::$currencies[$currencyCode])) {
            return self::$currencies[$currencyCode][1];
        }
        return '';
    }
}
